ticketee/config/routes.rb
Rails.application.routes.draw do
  get 'assets/show'

  namespace :admin do
    root 'base#index'

    resources :projects, only: [:new, :create, :destroy]
    resources :users
  end

  devise_for :users
  root 'projects#index'

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets
  end

  resources :assets, only: [:show, :new], path: :files
end

ticketee/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :author, class_name: "User"

  has_many :assets
  accepts_nested_attributes_for :assets, reject_if: :all_blank

  validates :title, presence: true
  validates :description, presence: true,
                          length: { minimum: 10 }
end

ticketee/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_project
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def new
    @ticket = @project.tickets.build
    @ticket.assets.build
    authorize @ticket, :create?
  end

  def create
    @ticket = @project.tickets.build(ticket_params)
    @ticket.author = current_user
    authorize @ticket, :create?

    if @ticket.save
      flash[:success] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash[:error] = "Ticket has not been created."
      render "new"
    end
  end

  def show
    authorize @ticket, :show?
  end

  def edit
    authorize @ticket, :update?
  end

  def update
    authorize @ticket, :update?

    if @ticket.update(ticket_params)
      flash[:success] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash[:error] = "Ticket has not been updated."
      render action: "edit"
    end
  end

  def destroy
    authorize @ticket, :destroy?
    @ticket.destroy
    flash[:success] = "Ticket has been deleted."

    redirect_to @project
  end

  private
    def ticket_params
      params.require(:ticket).permit(:title, :description,
        assets_attributes: [:asset, :asset_cache])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_ticket
      @ticket = @project.tickets.find(params[:id])
    end
end

ticketee/app/helpers/tickets_helper.rb
module TicketsHelper
end

ticketee/app/views/tickets/_form.html.erb
<div class='col-md-4'>
  <%= simple_form_for [@project, @ticket] do |f| %>
    <% if @ticket.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@ticket.errors.count, "error") %>
       prohibited this ticket from being saved:</h2>

       <ul>
       <% @ticket.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
       </ul>
     </div>
    <% end %>

    <%= f.input :title %>
    <%= f.input :description %>
    <div id="assets">
      <h3>Supporting Files</h3>
      <%= render partial: "assets/form", locals: { f: f, index: 0 } %>
    </div>
    <p>
      <%= link_to "Add another file", new_asset_path,
      remote: true, id: "add_file" %>
    </p>

    <%= f.button :submit, class: 'btn-primary' %>
  <% end %>
</div>

ticketee/app/views/tickets/edit.html.erb
<div class='row'>
  <h2>Editing a ticket in <%= @project.name %></h2>

  <%= render "form" %>
</div>

ticketee/app/views/tickets/new.html.erb
<div class='row'>
  <h2>New Ticket</h2>

  <%= render "form" %>
</div>

ticketee/app/views/tickets/show.html.erb
<div id='ticket'>
  <h2><%= @ticket.title %></h2>
  <% if policy(@ticket).update? %>
    <li><%= link_to "Edit Ticket", [:edit, @project, @ticket],
      class: "edit" %></li>
  <% end %>

  <% if policy(@ticket).destroy? %>
    <li><%= link_to "Delete Ticket", [@project, @ticket], method: :delete,
      data: { confirm: "Are you sure you want to delete this ticket?"},
      class: "delete" %></li>
  <% end %>
  <div id='author'>
    Created by <%= @ticket.author.email %>
  </div>
  <%= simple_format(@ticket.description) %>

  <% if @ticket.assets.any? %>
    <h4>Attached Files</h4>
    <div class="assets">
      <% @ticket.assets.each do |asset| %>
        <p>
          <%= link_to File.basename(asset.asset.url), asset_path(asset) %>
          (<%= number_to_human_size(asset.asset.size) %>)
        </p>
      <% end %>
    </div>
  <% end %>
</div>