ticketee/config/routes.rb
Rails.application.routes.draw do
  get 'assets/show'

  namespace :admin do
    root 'base#index'

    resources :projects, only: [:new, :create, :destroy]
    resources :users
  end

  devise_for :users
  root 'projects#index'

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets
  end

  resources :assets, only: [:show, :new], path: :files
end

ticketee/app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true

  has_many :tickets, dependent: :delete_all

  has_many :roles, dependent: :destroy

  def has_member?(user)
    roles.exists?(user_id: user)
  end

  [:manager, :editor, :viewer].each do |role|
    define_method "has_#{role}?" do |user|
      roles.exists?(user_id: user, role: role)
    end
  end
end

ticketee/app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render "new"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

ticketee/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = policy_scope(Project)
  end

  def edit
    authorize @project, :update?
  end

  def update
    authorize @project, :update?
    if @project.update(project_params)
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash.now[:alert] = "Project has not been updated."
      render "edit"
    end
  end

  def show
    authorize @project, :show?
  end

  private

  def set_project
    @project = Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking" +
                      " for could not be found."

      redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

ticketee/app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

ticketee/app/helpers/projects_helper.rb
module ProjectsHelper
end

ticketee/app/views/projects/_form.html.erb
<div class='col-md-4'>
  <%= simple_form_for(@project) do |f| %>
    <% if @project.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@project.errors.count, "error") %>
       prohibited this project from being saved:</h2>

       <ul>
         <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
    <% end %>

    <%= f.input :name %>
    <%= f.input :description %>

    <%= f.button :submit, class: 'btn-primary' %>
  <% end %>
</div>

ticketee/app/views/projects/edit.html.erb
<div class='row'>
  <h2>Edit project</h2>

  <%= render "form" %>
</div>

ticketee/app/views/projects/index.html.erb
<% admins_only do %>
  <ul class="actions">
    <li><%= link_to "New Project", new_admin_project_path,
      class: "new" %></li>
  </ul>
<% end %>

<h2>Projects</h2>
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

ticketee/app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>

<h1><%= @project.name %></h1>
<p><%= @project.description %></p>

<ul class="actions">
  <li>
    <% if policy(@project).update? %>
      <li><%= link_to "Edit Project",
        edit_project_path(@project), class: "edit" %></li>
    <% end %>
  </li>
  <% admins_only do %>
    <li><%= link_to "Delete Project",
      admin_project_path(@project),
      method: :delete,
      data: { confirm: "Are you sure you want to delete this project?" },
      class: "delete" %></li>
  <% end %>
</ul>

<% if policy(Ticket.new(project: @project)).create? %>
  <li><%= link_to "New Ticket", new_project_ticket_path(@project),
    class: "new" %>
  </li>
<% end %>

<div class='row'>
  <ul id='tickets'>
    <% @project.tickets.each do |ticket| %>
      <li>
        #<%= ticket.id %> -
        <%= link_to ticket.title, [@project, ticket] %>
      </li>
    <% end %>
  </ul>
</div>