ticketee/config/routes.rb
Rails.application.routes.draw do
  get 'assets/show'

  namespace :admin do
    root 'base#index'

    resources :projects, only: [:new, :create, :destroy]
    resources :users
  end

  devise_for :users
  root 'projects#index'

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets
  end

  resources :assets, only: [:show, :new], path: :files
end

ticketee/app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :ticket

  mount_uploader :asset, AssetUploader
end

ticketee/app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true

  has_many :tickets, dependent: :delete_all

  has_many :roles, dependent: :destroy

  def has_member?(user)
    roles.exists?(user_id: user)
  end

  [:manager, :editor, :viewer].each do |role|
    define_method "has_#{role}?" do |user|
      roles.exists?(user_id: user, role: role)
    end
  end
end

ticketee/app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  def self.available_roles
    ['manager', 'editor', 'viewer']
  end
end

ticketee/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :author, class_name: "User"

  has_many :assets
  accepts_nested_attributes_for :assets, reject_if: :all_blank

  validates :title, presence: true
  validates :description, presence: true,
                          length: { minimum: 10 }
end

ticketee/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :roles

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end

  def role_on(project)
    roles.find_by(project_id: project).try(:name)
  end
end

ticketee/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  after_action :verify_authorized, except: [:index],
    unless: :devise_controller?
  after_action :verify_policy_scoped, only: [:index],
    unless: :devise_controller?

  private

  def not_authorized
    redirect_to root_path, alert: "You aren't allowed to do that."
  end
end

ticketee/app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  skip_after_action :verify_authorized, only: [:new]

  def new
    @index = params[:index].to_i
    @ticket = Ticket.new
    @ticket.assets.build
    render layout: false
  end

  def show
    asset = Asset.find(params[:id])
    authorize asset, :show?
    send_file asset.asset.path, disposition: :inline
  end
end

ticketee/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = policy_scope(Project)
  end

  def edit
    authorize @project, :update?
  end

  def update
    authorize @project, :update?
    if @project.update(project_params)
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash.now[:alert] = "Project has not been updated."
      render "edit"
    end
  end

  def show
    authorize @project, :show?
  end

  private

  def set_project
    @project = Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking" +
                      " for could not be found."

      redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

ticketee/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if env['warden'].authenticate
      flash[:notice] = "Signed in successfully."

      redirect_to root_url
    else
      flash[:alert] = "Invalid email or password."
      render :new
    end
  end

  def destroy
    env["warden"].logout
    flash[:notice] = "You have signed out."
    redirect_to "/"
  end
end

ticketee/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_project
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def new
    @ticket = @project.tickets.build
    @ticket.assets.build
    authorize @ticket, :create?
  end

  def create
    @ticket = @project.tickets.build(ticket_params)
    @ticket.author = current_user
    authorize @ticket, :create?

    if @ticket.save
      flash[:success] = "Ticket has been created."
      redirect_to [@project, @ticket]
    else
      flash[:error] = "Ticket has not been created."
      render "new"
    end
  end

  def show
    authorize @ticket, :show?
  end

  def edit
    authorize @ticket, :update?
  end

  def update
    authorize @ticket, :update?

    if @ticket.update(ticket_params)
      flash[:success] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash[:error] = "Ticket has not been updated."
      render action: "edit"
    end
  end

  def destroy
    authorize @ticket, :destroy?
    @ticket.destroy
    flash[:success] = "Ticket has been deleted."

    redirect_to @project
  end

  private
    def ticket_params
      params.require(:ticket).permit(:title, :description,
        assets_attributes: [:asset, :asset_cache])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_ticket
      @ticket = @project.tickets.find(params[:id])
    end
end

ticketee/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "You have signed up successfully."
      redirect_to projects_path
    else
      render :new
    end
  end

  def show
  end

  private
    def user_params
      params.require(:user).permit(:name,
                                   :email,
                                   :password,
                                   :password_confirmation)
    end
end

ticketee/app/helpers/admin/base_helper.rb
module Admin::BaseHelper
  def roles
    hash = {}
    Role.available_roles.each { |role| hash[role.titleize] = role }
    hash
  end
end

ticketee/app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

ticketee/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

ticketee/app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join(" - ")
      end
    end
  end

  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end
end

ticketee/app/helpers/assets_helper.rb
module AssetsHelper
end

ticketee/app/helpers/projects_helper.rb
module ProjectsHelper
end

ticketee/app/helpers/sessions_helper.rb
module SessionsHelper
end

ticketee/app/helpers/tickets_helper.rb
module TicketsHelper
end

ticketee/app/helpers/users_helper.rb
module UsersHelper
end

ticketee/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% else %>
      Ticketee
    <% end %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class='container'>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "Ticketee", root_path, class: 'navbar-brand' %>
        </div>
        <ul class="nav navbar-nav">
          <li class='<%= 'active' if current_page?('/') %>'>
            <%= link_to "Home", root_path %>
          </li>
          <% admins_only do %>
            <li>
              <%= link_to "Admin", admin_root_path %>
            </li>
          <% end %>
          <% unless user_signed_in? %>
            <li class='<%= 'active' if current_page?('/users/sign_up') %>'>
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li class='<%= 'active' if current_page?('/users/sign_in') %>'>
              <%= link_to "Sign in", new_user_session_path %>
            </li>
          <% end %>
        </ul>

        <% if user_signed_in? %>
          <div class="collapse navbar-collapse">
            <div class="navbar-text navbar-right">
              Signed in as <%= current_user.email %> &middot;
              <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
            </div>
          </div>
        <% end %>
      </div>
    </nav>

    <% flash.each do |key, message| %>
      <div class='alert alert-<%= key %>'>
        <%= message %>
      </div>
    <% end %>


    <div class='col-md-12'>
      <%= yield %>
    </div>
  </div>
</body>
</html>