ticketee/config/routes.rb
Rails.application.routes.draw do
  get 'assets/show'

  namespace :admin do
    root 'base#index'

    resources :projects, only: [:new, :create, :destroy]
    resources :users
  end

  devise_for :users
  root 'projects#index'

  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets
  end

  resources :assets, only: [:show, :new], path: :files
end

ticketee/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :roles

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end

  def role_on(project)
    roles.find_by(project_id: project).try(:name)
  end
end

ticketee/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_projects, only: [:new, :create, :edit, :update]

  def index
    @users = User.order(:email)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    build_roles_for(@user)

    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been created."
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end

    ActiveRecord::Base.transaction do
      @user.roles.clear
      build_roles_for(@user)

      if @user.update(user_params)
        flash[:notice] = "User has been updated."
        redirect_to admin_users_path
      else
        flash.now[:alert] = "User has not been updated."
        render "edit"
        raise ActiveRecord::Rollback
      end
    end
  end

  def destroy
    if @user == current_user
      flash[:alert] = "You cannot delete yourself!"
    else
      @user.destroy
      flash[:notice] = "User has been deleted."
    end

    redirect_to admin_users_path
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :admin)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def set_projects
      @projects = Project.all
    end

    def build_roles_for(user)
      role_data = params.fetch(:roles, [])
      role_data.each do |project_id, role_name|
        if role_name.present?
          user.roles.build(project_id: project_id, role: role_name)
        end
      end
    end
end

ticketee/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "You have signed up successfully."
      redirect_to projects_path
    else
      render :new
    end
  end

  def show
  end

  private
    def user_params
      params.require(:user).permit(:name,
                                   :email,
                                   :password,
                                   :password_confirmation)
    end
end

ticketee/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

ticketee/app/helpers/users_helper.rb
module UsersHelper
end

ticketee/app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, user] do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>

  <div class="page-header">
    <h2>Roles</h2>
  </div>

  <table class="roles">
    <% @projects.each do |project| %>
      <tr>
        <th><%= label_tag dom_id(project), project.name %></th>
        <td>
          <%= select_tag dom_id(project), options_for_select(roles,
            @user.role_on(project)), name: "roles[#{project.id}]",
            include_blank: true %>
        </td>
      </tr>
    <% end %>
  </table>

  <%= f.button :submit, class: "btn btn-primary" %>

  <%= f.input :admin, label: "Is an admin?" %>
<% end %>

ticketee/app/views/admin/users/edit.html.erb
<div class="page-header">
  <h1>Edit User</h1>
</div>

<%= render "form", user: @user %>

ticketee/app/views/admin/users/index.html.erb
<div class="page-header">
  <h1>Users</h1>

  <ul class="actions">
    <li><%= link_to "New User", new_admin_user_path, class: "new" %></li>
  </ul>
</div>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user, [:admin, user] %></li>
  <% end %>
</ul>

ticketee/app/views/admin/users/new.html.erb
<div class="page-header">
  <h1>New User</h1>
</div>

<%= render "form", user: @user %>

ticketee/app/views/admin/users/show.html.erb
<div class="page-header">
  <h1><%= @user %></h1>

  <ul class="actions">
    <li><%= link_to "Edit User", [:edit, :admin, @user],
      class: "edit" %></li>

    <li><%= link_to "Delete User", [:admin, @user], method: :delete,
        data: { confirm: "Are you sure you want to delete this user?"},
        class: "delete" %></li>
  </ul>

  <% if @user.roles.any? %>
    <ul>
      <% @user.roles.each do |role| %>
        <li><%= role.project.name %>: <%= role.role.titleize %></li>
      <% end %>
    </ul>
  <% else %>
    <p>This user has no roles.</p>
  <% end %>
</div>